### ISSUE TITLE
Help with usage

### ISSUE THREAD

**Issue by cemtuna** [evermeer/AlamofireJsonToObjects#40]
Hi my friends, i tried all of bug fixing but i couldn't be success to use alamofirejsontoobjects in my swift 3.0.2 project with Xcode 8.2.1. My project is in link below. Please help me. 
http://jmp.sh/rAS7YCX

**Comment by evermeer** [comment]
Hmm... For some reason you kept getting the warning:

`Target 'Pods-Tombus' of project 'Pods' was rejected as an implicit dependency for 'Pods_Tombus.framework' because its architectures 'arm64' didn't contain all required architectures 'armv7 arm64'
`

After setting your projects 'Build Active Architecture Only' to Yes which is the default it went away. Why do you always want to build for all architectures?

**Comment by evermeer** [comment]
One other thing. You should change your pod file to:

```
platform :ios, '8.0'

target 'Tombus' do
  use_frameworks!
  pod "EVReflection/Alamofire"
end
```

I have moved the AlamofireJsonToObjects into the EVReflection library so that when I change something everything will always be tested. There are now also nice extensions for RxSwift and ReactiveSwift
