### ISSUE TITLE
Problems after updating the pod and to Swift4

### ISSUE THREAD

**Issue by Dbigshooter** [evermeer/AlamofireJsonToObjects#43]
After updating the pod and to Swift 4, image below shows:

<img width="388" alt="screen shot 2018-03-22 at 18 57 17" src="https://user-images.githubusercontent.com/6803648/37789098-54fbb354-2e03-11e8-9941-00c3b40e4153.png">

**Comment by evermeer** [comment]
As you can see at the top in the readme you should switch to:

pod 'EVReflection/Alamofire'

Functionally it's identical. AlamofireJsonToObjects is not maintained anymore. Updates and fixes are only in EVReflection. AlamofireJsonToObjects is not available for swift 4.

This was done so that there is always a consistent version where all variants will always be checked in the unit tests.
